name: 清理所有工作流运行记录
on:
  workflow_dispatch:
    inputs:
      count:
        description: '最多清理的运行次数（每个工作流）'
        required: false
        default: '20'
      delete_failed:
        description: '删除失败的运行记录？'
        required: false
        type: boolean
        default: true
      delete_success:
        description: '删除成功的运行记录？'
        required: false
        type: boolean
        default: true
      delete_cancelled:
        description: '删除已取消的运行记录？'
        required: false
        type: boolean
        default: true
      reverse_order:
        description: '从旧到新开始清理？'
        required: false
        type: boolean
        default: false

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
